<?php

/**
 * @file
 * Defines options to control how the Read More link is displayed on teasers.
 */

/**
 * Implements hook_hook_info().
 */
function readmorecontrol_hook_info() {
  $hooks = array(
    'field_display_alter' => array(
      'group' => 'node',
    ),
    'node_view' => array(
      'group' => 'node',
    ),
    'form_node_type_form_alter' => array(
      'group' => 'admin',
    ),
    'form_field_ui_field_edit_form_alter' => array(
      'group' => 'admin',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_help().
 */
function readmorecontrol_help($path, $arg) {
  switch ($path) {
    case 'admin/help#readmorecontrol':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Read More Control module adds settings to node content types, and node field instances to control when the %readmore link is displayed in a teaser.</p>',
        array('%readmore' => t('Read More')));
      return $output;
  }
}
