<?php

/**
 * @file
 * Defines options to control how the Read more link is displayed on teasers.
 */

/**
 * Implements hook_hook_info().
 */
function readmorecontrol_hook_info() {
  $hooks = array(
    'field_display_alter' => array(
      'group' => 'node',
    ),
    'node_view' => array(
      'group' => 'node',
    ),
    'form_node_type_form_alter' => array(
      'group' => 'admin',
    ),
    'form_field_ui_field_edit_form_alter' => array(
      'group' => 'admin',
    ),
    'node_type_update' => array(
      'group' => 'admin',
    ),
    'node_type_delete' => array(
      'group' => 'admin',
    ),
  );

  return $hooks;
}


/**
 * Implements hook_help().
 */
function readmorecontrol_help($path, $arg) {
  switch ($path) {
    case 'admin/help#readmorecontrol':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Read More Control module adds settings to node content types, and node field instances to control when the "Read more" link is displayed in a teaser.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function readmorecontrol_menu() {
  $items['admin/config/content/read-more-control'] = array(
    'title' => 'Read more settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('readmorecontrol_admin_settings_form'),
    'description' => 'Configure the Read more link settings.',
    'access arguments' => array('administer site configuration'),
    'file' => 'readmorecontrol.admin.inc',
  );
  return $items;
}
